### ISSUE TITLE
Change the GenesisProtocol parameter defaults

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#104]
Current GenesisProtocol parameter defaults don't make sense, at least not `preBoostedVotePeriodLimit` which currently defaults to 60 seconds.

@orenyodfat @tibetsprague @leviadam Suggestions requested, thanks!

Here are the current defaults:

```
        boostedVotePeriodLimit: 60,
        governanceFormulasInterface: Utils.NULL_ADDRESS,
        minimumStakingFee: 0,
        preBoostedVotePeriodLimit: 60,
        preBoostedVoteRequiredPercentage: 50,
        proposingRepRewardConstA: 1,
        proposingRepRewardConstB: 1,
        quietEndingPeriod: 0,
        stakerFeeRatioForVoters: 1,
        thresholdConstA: 1,
        thresholdConstB: 1,
        votersGainRepRatioFromLostRep: 80,
        votersReputationLossRatio: 10,
```

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change the GenesisProtocol parameter defaults](https://trello.com/c/cufgh0W8/96-change-the-genesisprotocol-parameter-defaults)

**Comment by dkent600** [comment]
We need to know this not just for the Arc.js API, but for the params applied to the Genesis DAO at migration time.

@leviadam @orensokolowsky1

**Comment by orenyodfat** [comment]
Yes , as far as I know there is still no agreement on the default Genesis Protocol params. 
As far it can be override , i do not see any rush for that.

@dkent600 how it is related to Genesis DAO ?

**Comment by dkent600** [comment]
@orenyodfat 

> how it is related to Genesis DAO ?

See [here](https://github.com/daostack/arc.js/blob/cleanupMigrationScript/migrations/2_deploy_organization.js)

All of Genesis' proposal-generating schemes require for their parameters a voting machine and the voting machine's own parameters.  They all use GenesisProtocol as their voting machine.

**Comment by dkent600** [comment]
We've got the defaults for the migration now ([here](https://github.com/daostack/arc.js/commit/8e27e181be96230ec0c82cdb08ce9822a1f681ee)).

So there just remain the defaults for `DAO.new`.

**Comment by dkent600** [comment]
@leviadam I want to make the defaults for `Dao.new` be the same as the params we use for the Genesis DAO.  Is that OK for you?

**Comment by dkent600** [comment]
https://daostack.slack.com/archives/G8SJXKBK4/p1521028110000317
