### ISSUE TITLE
Review migration script

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#105]
Review the migration script in advance of the upcoming audit.

First step:  Make it look prettier, cleaner, more readable.

Second step:  Anticipate auditor's concerns.

**Comment by dev-matan-tsuberi** [comment]
Do you mean review it from a security standpoint?

**Comment by dkent600** [comment]
@dev-matan-tsuberi 

> Do you mean review it from a security standpoint?

Probably, but best by far to pose the question to @leviadam and @orenyodfat

**Comment by dev-matan-tsuberi** [comment]
Well, it's us who control the migrations script, no hacker could change it, and as long as the individual contracts are secure and do what is intended the whole should be secure as well, no?

**Comment by dkent600** [comment]
Someone mentioned that the auditor might want to look at how "the contracts are connected" by the migration scripts.  Also of interest might the contract parameter values set by the script.

**Comment by dkent600** [comment]
See the most recent proposed changes in this branch:  https://github.com/daostack/arc.js/tree/cleanupMigrationScript

**Comment by dkent600** [comment]
Closing with the clean up.  Any issues found during auditing can be reported separately.
