### ISSUE TITLE
`GenesisProtocolWrapper.stake` needs to approve before spending.

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/arc.js#119]
approval shouldn't be done in the frontend.

**Comment by dev-matan-tsuberi** [comment]
Alchemy needs this for: https://trello.com/c/FeNccqAY/9-stake-on-a-proposals

**Comment by orenyodfat** [comment]
I would suggest to add a configuration flag for auto approve txs.
- the flag should be approve by default.
- it should documented. 
- user can set that to false if she would like to..
