### ISSUE TITLE
Estimate gas for each transaction

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc.js#120]
Set the gasLimit for each transaction to the value returned by web3's estimateGas function https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethestimategas

This should make working with MetaMask easier since it seems to use that to determine the max gasLimit for each transaction

**Comment by tibetsprague** [comment]
Although will this make every transaction significantly slower? We should check

**Comment by dkent600** [comment]
@tibetsprague This doesn't make sense to me.  Why would MM override the gasLimit we are passing to Truffle?

**Comment by dkent600** [comment]
[This PR](https://github.com/daostack/arc.js/pull/127) should solve this problem
