### ISSUE TITLE
Add functionality to get total DAO reputation when a proposal was executed

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc.js#125]
This can be pulled from the GenesisProtocol ExecutedProposal event, the _totalReputation arg. 
I would like a function to grab this for a single proposal at least but should we pull it for all proposals when getDaoProposals is called too?

**Comment by tibetsprague** [comment]
Even more important ExecuteProposalEventResult doesn't include the _totalReputation arg, so i cant even get it at all right now

**Comment by dkent600** [comment]
See `GenesisProtocol.getTotalReputationSupply`.

As for the event, unless that event arg was added later, this is just a typings issue.  Just cast the event to `any` and you can grab whatever you  want from  it.  In the meantime, I'll respond to the issue by fixing the interface definition.

You can also get total reputation any time by calling `Dao.reputation().totalSupply()`

**Comment by dkent600** [comment]
As for adding to getDaoProposals, it wouldn't make sense because it is always gong to have the same value, that of `Dao.reputation().totalSupply()`

**Comment by tibetsprague** [comment]
im talking about getting the total Reputation at the time that the proposal was executed, which for now only exists on the ExecuteProposal event. @orenyodfat we may consider adding it to the GenesisProtocol Proposal struct, so we can pull all useful information from there instead of having to get the event for executed proposals?

**Comment by dkent600** [comment]
Fixed the typings and added GenesisProtocol.getExecutedDaoProposals.
