### ISSUE TITLE
Increase gasLimit for forgeOrg

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#128]
Per @orenyodfat 

Please note that forgeOrg consume more gas as the number of founders increase.
My suggestion is to set 'gasLimit-deployment' for this function to be on the safe side.

**Comment by dkent600** [comment]
Note this change could result in hassles with Metamask....

**Comment by dkent600** [comment]
@orenyodfat With respect to gas, how many founders should we be able to handle?

**Comment by orenyodfat** [comment]
you should try and see :) .

**Comment by dkent600** [comment]
@orenyodfat  Just did forty founders, no problem.  Ganache, 1000 tokens, 1000 reputation

**Comment by dkent600** [comment]
@orenyodfat I am inclined to think that when creating a DAO, in order to support the maximum possible number of founders, we should dynamically determine the current network block gas limit and supply that.  (I believe this would be easy to do.)

What do you think?

The only remaining question, I think, would then be to communicate to users, via documentation or at runtime in the app, how many founders they can expect to be able to create, given the current block gas limit.

**Comment by orenyodfat** [comment]
The code should look like 
> var gasPerFounder = 50000;
var gas = founders.length *gasPerFounder + gasLimit;
if gas > mainNetGasLimt {
  gas = mainNetGasLimt;
}
var tx = await daoCreator.forgeOrg("testOrg","TEST","TST",founders,foundersToken,foundersReputation,0,{gas: gas});

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Increase gasLimit for forgeOrg](https://trello.com/c/gWpuGRb8/114-increase-gaslimit-for-forgeorg)

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Increase gasLimit for forgeOrg](https://trello.com/c/gWpuGRb8/114-increase-gaslimit-for-forgeorg)
