### ISSUE TITLE
upgrade arc.js to Arc v37

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#151]
- gas limit change => 5100000
- controller now has getNativeReputation
- method for deploying DaoCreator has changed (deploy ControllerCreator first, no extra gas)
- upgrade ganache-cli version
- TokenCapGC renamed params => parameters
- AbsoluteVote has new refreshReputation function

GP changes
- change to GP params (removed genesisProtocolFormulasInterface)
- proposal.boostedVotePeriodLimit  => proposal.currentBoostedVotePeriodLimit
- added proposal.paramsHash (these are the params of the scheme itself)
- threshold() now takes proposalId param
- currentBoostedVotePeriodLimit returns int instead of unint
- totalReputationSupply is gone
- proposalStatus now returns reputation
- propose method no longer has _paramsHash parameter

**Comment by dkent600** [comment]
- gas limit change => 5000000

-controller now has getNativeReputation
- method for deploying DaoCreator has changed (deploy ControllerCreator first, no extra gas)
- upgrade ganache-cli version

GP changes
- change to GP params (revmoed genesisProtocolFormulasInterface)
- proposal.boostedVotePeriodLimit  => proposal.currentBoostedVotePeriodLimit
- added proposal.paramsHash (these are the params of the scheme itself)
- threshold() now takes proposalId param
- currentBoostedVotePeriodLimit returns int instead of unint
- totalReputationSupply is gone
- proposalStatus now returns reputation

**Comment by orenyodfat** [comment]
Please rename to arc v 37.as 36 has a test issue.
gas limit change => 5100000

totalReputationSupply is gone ? 

currentBoostedVotePeriodLimit returns int instead of unint ?

> propose method no longer has _paramsHash parameter 
This is relevant to arc.js ?

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [upgrade arc.js to Arc v37](https://trello.com/c/Pnlz1c8z/106-upgrade-arcjs-to-arc-v37)

**Comment by dkent600** [comment]
Done
