### ISSUE TITLE
Is threshold const A too small in migration?

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/arc.js#159]
In the migration we set `threshold cost A` to be 2, this means that if there are no boosted proposals, the threshold is exactly 2 **in wei** (meaning the smallest unit of the `DAOToken`). 
This seems very low and maybe a mistake.

In alchemy for example, we stake in units of `GEN`, which are 10^18 wei. So the threshold is practically almost zero.

**Comment by dkent600** [comment]
@leviadam @tibetsprague @orenyodfat 

Would this question of units affect any other settings?

**Comment by tibetsprague** [comment]
oh interesting, probably proposingRepRewardConstB and proposingRepRewardConstA too?

**Comment by orenyodfat** [comment]
Well, yes.
We might modify these values in the future to be relative to total token/reputation supply.
Till then ,thresholdCostA ,proposingRepRewardConstB & proposingRepRewardConstA need to be in wei units.
please note that current arc version won't a alow thresholdCostA over 0xff.I will fix that soon..

**Comment by dkent600** [comment]
@orenyodfat @dev-matan-tsuberi 

Are we to leave the default values as they are?

**Comment by dev-matan-tsuberi** [comment]
@dkent600 I talked to @orenyodfat yesterday, we decided that we should either:
1. give founders 1000 GENi (1 GEN = 10^18 GENi)
2. change `thresholdConstA` to be 2*10^18

I'm all for the second option, as it preserves the divisibility of the token (you can't divide ` GENi into fractions).

**Comment by tibetsprague** [comment]
yeah lets definitely change thresholdConstA to be in WEI, that seems much preferable to me

**Comment by orenyodfat** [comment]
thresholdCostA ,proposingRepRewardConstB & proposingRepRewardConstA need to be in wei units.

**Comment by dev-matan-tsuberi** [comment]
@orenyodfat well, then let's go for the first option and keep in mind to fix it in the future. In the meantime, alchemy will work in GENi units.

**Comment by orenyodfat** [comment]
@dev-matan-tsuberi i might not clarify myself properly ...I vote for option 2 above.
- change thresholdConstA to be 2*10^18
same as for proposingRepRewardConstB & proposingRepRewardConstA

**Comment by dev-matan-tsuberi** [comment]
@orenyodfat Oh, I thought you were saying that we can't change it to 2*10^18 because it can't be bigger than 0xff.

**Comment by orenyodfat** [comment]
This was already addressed  https://github.com/daostack/arc/blob/master/contracts/VotingMachines/GenesisProtocol.sol#L126

**Comment by dev-matan-tsuberi** [comment]
Why do we enforce those restrictions?
