### ISSUE TITLE
Refactor contract wrappers access, round two

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#160]
Refactor how contract wrappers are served up.

At the very least, improve the documentation [here](https://daostack.github.io/arc.js/Home/#how-to-obtain-a-contract-wrapper)
- explain again what a wrapper is
- provide use cases that add value to each way of obtaining a wrapper
- move docs for the `WrapperService` out of the Home page, replacing it with a link to its API page, "for further reference").

Potential API improvements:
- `WrapperService.wrappers.UpgradeScheme` can be accessible via `ContractWrappers.UpgradeScheme`
- `WrapperService.factories.UpgradeScheme` can be accessible via `ContractWrapperFactories.UpgradeScheme`
- `WrapperService.wrappersByType.schemes` can be accessible via `ContractWrapperTypes.schemes`

... where `ContractWrappers`,  `ContractWrapperFactories` and `ContractWrapperTypes` are accessible via `import`.  The idea here is to hide the WrapperService, subtracting one level of indirection in the access to these three collections.

- each wrapper can have a static property `factory` that is the factory for the contract (maybe would be protected).
- each wrapper could have static `at` and `new` and `deployed` methods that are implemented internally by the wrapper's factory.  (Not 100% sure this is reasonably feasible -- gotta confirm)

The idea of the above two items is to enable access to the factory methods via the wrappers themselves.  This is closer to what Truffle does, which might be appreciated by developers accustomed to working with Truffle.

- rename `UpgradeScheme` to `UpgradeSchemeFactory` and `UpgradeSchemeWrapper` to `UpgradeScheme`

`import { UpgradeScheme } from "@daostack/arc.js"` would return the wrapper instance hydrated as it was deployed.

**Comment by dkent600** [comment]
@tibetsprague Can you please look at this for questions or suggestions?

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor contract wrappers access, round two](https://trello.com/c/2wW8nIMe/109-refactor-contract-wrappers-access-round-two)

**Comment by tibetsprague** [comment]
this does sound better to me, although im not sure about UpgradeSchemeWrapper to UpgradeScheme, might be clearer to keep Wrapper in the name

**Comment by dkent600** [comment]
> this does sound better to me

@tibetsprague I want to make sure it sounds not just "better", but best.  Can you think of any ways to make it best?  :-)

**Comment by dkent600** [comment]
Here is what I've done:

- updated docs
- `WrapperService.wrappers` is accessible via `ContractWrappers`
- `WrapperService.factories` is accessible via `ContractWrapperFactories`
- `WrapperService.wrappersByType` is accessible via `ContractWrappersByType`
- `WrapperService.wrappersByAddress` is accessible via `ContractWrappersByAddress`

... where each is accessible via `import`.

- each wrapper now has a public _non_-static property `factory` that is the factory for the contract. **There are no additional 'at' or 'new' methods** on the wrappers.
- renamed `UpgradeScheme` to `UpgradeSchemeFactory`  (this is the only **breaking change**)
