### ISSUE TITLE
Add function to ContributionRewardWrapper to get current redeemable rewards

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc.js#164]
I need to show the user when they click redeem what rewards they will be getting at that moment,

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add function to ContributionRewardWrapper to get current redeemable rewards](https://trello.com/c/uKB2n0XY/112-add-function-to-contributionrewardwrapper-to-get-current-redeemable-rewards)

**Comment by dkent600** [comment]
@tibetsprague Does [getBeneficiaryRewards](https://daostack.github.io/arc.js/api/classes/ContributionRewardWrapper/#getbeneficiaryrewards) not work for this?  If not, what do you need that is different?

**Comment by tibetsprague** [comment]
First of all that returns data for all proposals, I want to be able to lookup one proposal. Also it looks like that returns the total amount that can be redeemed, and the amount left to redeem in total, not what can currently be redeemed at that moment.

**Comment by dkent600** [comment]
@tibetsprague 

> First of all that returns data for all proposals

You _can_ filter by proposal Id, see here:
https://daostack.github.io/arc.js/api/interfaces/GetBeneficiaryRewardsParams/

> it looks like that returns the total amount that can be redeemed, and the amount left to redeem in total, not what can currently be redeemed at that moment.

Here is a PR for you:  https://github.com/daostack/arc.js/pull/166
