### ISSUE TITLE
Remove duplicate events

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/arc.js#176]
Watching events may fire the callback twice with the same event (same tx hash). 
This is a known web3.js behaviour (https://github.com/ethereum/web3.js/issues/398).

Possible solution may be:
1. wait for a minimum number of confirmation blocks.
2. suppress duplicate events by remembering previous tx hashs (not scalable).

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove duplicate events](https://trello.com/c/CwqT1C26/120-remove-duplicate-events)

**Comment by YoonjaeYoo** [comment]
@dev-matan-tsuberi When do you think it would be fixed?
We are suffering from this issue.
Thank you.

**Comment by dkent600** [comment]
@dev-matan-tsuberi @YoonjaeYoo 

Have you tried this suggestion:  https://github.com/ethereum/web3.js/issues/398#issuecomment-213331868 ?

**Comment by dkent600** [comment]
@YoonjaeYoo you should find that dups are now being removed in the latest release of Arc.js.  Let us know if not, thanks.
