### ISSUE TITLE
Refactor Organization.new

### ISSUE THREAD

**Issue by orenyodfat** [daostack/Arc.js#18]
Not all scheme use same parameters and the order is not forced in any way.
Some scheme does not use even voting machines.
I think that one possible solution will be to maintain a table which define the parameters needed for each scheme and the code should act accordingly.

**Comment by dkent600** [comment]
@orenyodfat I don't think this is a problem.  Please review [this code](https://github.com/daostack/arc-js/blob/65677123f14305918879eb1a098c4ebc89c6b06a/lib/schemeregistrar.js#L215) and close this issue if you agree.  Thanks.

**Comment by orenyodfat** [comment]
@dkent600 how about a scheme like simpleICO which does not even use voting ?

**Comment by dkent600** [comment]
It would look like this:

```
 async setParams(params) {
    return await this._setParameters(
        params.cap,
        params.price,
        params.startBlock,
        params.endBlock,
        params._beneficiary,
        params._admin);
  }
```

**Comment by orenyodfat** [comment]
So org.new need to be refactor ? To not use voting machine and other params
by default ...or I am missing something here

**Comment by dkent600** [comment]
We will need to make changes to accommodate other voting machines.  I view that as a separate issue from this one, but one we will definitely be doing, of course

In the meantime, I'm not seeing any other code changes arising out of this issue.

**Comment by orenyodfat** [comment]
> We will need to make changes to accommodate other voting machines.

Not sure that you even need to accommodate voting machines in organization.new as it should come as a parameter along with each scheme.
Default params and schemes might also come as params to the organization.new.   
Some scheme even do not use Voting machines.
If a scheme does getting a voting machine  as a parameters ,it usually can get any type of voting machine which is align with IntVoteInterface.
If a user would like to create an org which use a scheme which use voting machine , I guess that the user should be given  an option to choose the voting machine type and its parameters. 

In general , the parameters for each scheme should come as a parameter for the organization.new.
I guess that the organization.new cannot do any assumption on that unless the user choose to use defaults parameters set.

**Comment by dkent600** [comment]
> If a user would like to create an org which use a scheme which use voting machine , I guess that the user should be given an option to choose the voting machine type and its parameters.

Yes, that is how Alchemy is already designed to work.

Again, I think there is room for refactoring the structure of the config that is input to `organization.new`, but it has nothing to do with `utils.setParams`, which is working correctly.

**Comment by dkent600** [comment]
OK, if this issue is going to be about refactoring `organization.new` in general:

Two things we could do as part of refactoring:

1. provide information about each scheme within each individual scheme config object rather than mixing the information about every scheme altogether at the root level
2. consistent with how the individual scheme wrappers work: require that the caller, when providing scheme parameters, provide the hash value of the parameters, rather than the raw, individual parameters

**Comment by orenyodfat** [comment]
👍

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor Organization.new](https://trello.com/c/tZB40Yzd/34-refactor-organizationnew)

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor Organization.new](https://trello.com/c/tZB40Yzd/34-refactor-organizationnew)

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Configure voting machines per-scheme when creating an organization](https://trello.com/c/40RnZ3rc/45-configure-voting-machines-per-scheme-when-creating-an-organization)
