### ISSUE TITLE
`dao.reputation` does not have the `Burn` event.

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [daostack/arc.js#180]
It's also missing from the abi in `@daostack/arc.js/migrated_contracts/Reputation.json`.
It **does** exist in Arc in `build/contracts/Reputation.json` after building.

**Comment by dkent600** [comment]
@dev-matan-tsuberi The Burn event it is there for me.  What version of arc.js are you looking at?

**Comment by dev-matan-tsuberi** [comment]
@dkent600 using `0.0.0-alpha.40`

**Comment by dkent600** [comment]
@dev-matan-tsuberi  `Burn` is new.  The current version is 0.0.0-alpha.42.  Check that.
