### ISSUE TITLE
NewDaoConfig doesn't include schemes

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc.js#182]
So you can't pass in schemes when creating a new DAO, even though you are supposed to be able to do

**Comment by dkent600** [comment]
@tibetsprague Can you please describe what you are doing and what is happening? Thanks,

**Comment by tibetsprague** [comment]
dao = await DAO.new({
      name: "Skynet",
      tokenName: "Tokens of skynet",
      tokenSymbol: "SNT",
      founders: [
        {
          address: accounts[0],
          reputation: web3.toWei(1000),
          tokens: web3.toWei(40)
        }
      ],
      schemes: [
        { name: "SchemeRegistrar" },
        { name: "UpgradeScheme" },
        { name: "GlobalConstraintRegistrar" }
      ]
    });

returns a type error that schemes does not exist on NewDaoConfig

**Comment by dkent600** [comment]
@tibetsprague FYI until this is fixed you can work-around by casting the config object to <any>
