### ISSUE TITLE
Clean up and fill out automated tests

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#19]
The automated tests currently stand as they were when arc-js was forked from arc (daostack).  There persist some daostack-specific tests that can be removed.  It would not take much imagination to think of new tests that could be added.

Also would like to see helper/perTest code be refactored, perhaps to emulate the patterns being used in the daostack tests (like `setup`).

**Comment by leviadam** [comment]
The current idea is that the backend is doing its own tests, which are not using the library and attend each contract separately. I think here we should  build tests which are using the tests and are more system as a whole oriented.

**Comment by dkent600** [comment]
@leviadam Can you please clarify:

> I think here we should build tests _which are using the tests_

(which tests?)

**Comment by leviadam** [comment]
Type, fixed.

**Comment by tibetsprague** [comment]
Need to see what our current coverage is and what we're missing
