### ISSUE TITLE
proposingRepRewardConstB is way way way too big

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc.js#196]
Right now the default value is web3.toWei(5).This means that passing one proposal is giving a reputation reward to the proposer that looks like 50000000000000000000 even when the DAO only has 10 reputation total, and AFTER converting from WEI :) 

So, proposingRepRewardConstB needs to not be converted to WEI and also probably shouldn't be greater than 1.

**Comment by tibetsprague** [comment]
https://github.com/daostack/arc/issues/438

**Comment by dkent600** [comment]
@orenyodfat
