### ISSUE TITLE
Cannot read property 'setParameters' of null

### ISSUE THREAD

**Issue by goodstemy** [daostack/arc.js#226]
I getting an error when I try to create new DAO with schemes by this tutorial: https://daostack.github.io/arc.js/Daos/#creating-a-new-dao-with-schemes

Code: 
<img width="487" alt="2018-05-21 20 37 35" src="https://user-images.githubusercontent.com/8494692/40324080-b365b404-5d37-11e8-8c20-1b5ff801723d.png">
Logs:
<img width="1400" alt="2018-05-21 20 37 42" src="https://user-images.githubusercontent.com/8494692/40324081-b3a8d28e-5d37-11e8-9931-54f278929e65.png">

**Comment by dkent600** [comment]
@goodstemy  Add "SchemeRegistrar" to your filter and report back what happens.
