### ISSUE TITLE
TokenCapGc is not a scheme

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#233]
`TokenCapGC` is not a scheme and should not purport to being one by inheriting from `ContractWrapperBase`.

Rather, `ContractWrapperBase` should be just about generic wrappers and less about schemes.  Probably should have a new subclass just for schemes.

**Comment by orenyodfat** [comment]
@dkent600 ?

**Comment by dkent600** [comment]
Replaced by #338
