### ISSUE TITLE
Separate deployment of the Genesis DAO in the Arc.js deployment script

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#239]
Deploy the Genesis DAO in a separate deployment script, or perhaps better, make it an optional part of the deployment script.

Applications will still want to be able to deploy both, at least to ganache, so there should remain a single script that does both.

**Comment by dkent600** [comment]
@orenyodfat

**Comment by orenyodfat** [comment]
better to have it in two separate scripts.
first script deploy : 
- Schemes 
- VotingMachines 
- DaoCreator

second script create dao and register schemes: 
- get a set of scheme (which already been deployed at the first script).
- dao params (token name, symbol,founders....).

user may choose to avoid using the second script .

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Separate deployment of the Genesis DAO in the Arc.js deployment script](https://trello.com/c/EQ1e0zoW/144-separate-deployment-of-the-genesis-dao-in-the-arcjs-deployment-script)
