### ISSUE TITLE
Catch up with new Arc schemes and other entities

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#24]
We need to survey Arc to find out what new schemes and other entities need to be pulled in, for example,  but not limited-to, new voting machines.

**Comment by tibetsprague** [comment]
we need to do a survey to find out what functionality is missing

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Catch up ArcJS wrappers to match all contracts and necessary functionality in Arc](https://trello.com/c/QknArAiV/33-catch-up-arcjs-wrappers-to-match-all-contracts-and-necessary-functionality-in-arc)

**Comment by dkent600** [comment]
Some that do not at this writing have wrappers:

GenesisScheme
OrganizationRegister
SimpleICO
VestingScheme
VoteInOrganizationScheme
EmergentVoteScheme
QuorumVote

**Comment by dkent600** [comment]
What we will do for this:

* GenesisScheme
* VestingScheme
* VoteInOrganizationScheme
* Governance

Others can be requested in future tickets.

**Comment by dkent600** [comment]
Done
