### ISSUE TITLE
Provide choice of Universal or non-Universal controller when creating a DAO

### ISSUE THREAD

**Issue by dkent600** [daostack/Arc.js#26]
In `Organization.new` We should provide a choice of Universal and non-Universal controller when creating a new DAO.

The default should be, which?  @orenyodfat

**Comment by orenyodfat** [comment]
I think Organization.new should get that as a param and support both.
We might need this issue at the UI layer.

**Comment by dkent600** [comment]
> We might need this issue at the UI layer.

yes, both places, voila:  https://github.com/daostack/Alchemy-Aurelia/issues/12

**Comment by leviadam** [comment]
I think the default should be universal.

**Comment by dkent600** [comment]
@leviadam This has not been implemented.  Arc-js does not yet provide an option in Organization.new.  Should this have been closed?

**Comment by leviadam** [comment]
OK. We can keep open as a reminder.

**Comment by dkent600** [comment]
Done
