### ISSUE TITLE
Complete documentation

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#27]
We have a lot to do with regard to documentation.

Questions:

Do we retain the docs folder, or put everything in the root README.md?
Do we add the automated creation of the API from code comments?

@orenyodfat 

Update readme.md with current information about the package, coding examples, (including API reference?) and some good build instructions, that is, package script documentation.

(See package-scripts.js for some of the latter.)

**Comment by leviadam** [comment]
I think we decided to start with the README

**Comment by tibetsprague** [comment]
Yeah I liked putting it all in the README for now

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Complete documentation of the library](https://trello.com/c/GKJTK9H6/32-complete-documentation-of-the-library)

**Comment by dkent600** [comment]
#63 remains as a separate task.
