### ISSUE TITLE
Gas Estimation issue

### ISSUE THREAD

**Issue by orenyodfat** [daostack/arc.js#280]
solidity v 0.4.24 has an issue(bug) which cause infinite gas estimation when using libraries. 
Arc package V44 use solc v 0.4.24 and is using libraries .(GenesisProtocol contract as well).
https://github.com/ethereum/solidity/issues/4471

Does arc.js will return max gasLimit in this case ?
I guess that in this case it should return  a fix reasonable value ..(e.g 2,000,000 for gp txs).

**Comment by dkent600** [comment]
Arc.js caps every gas estimation at latestBlock.gasLimit - 100000
