### ISSUE TITLE
remove truffle-core-migrate-without-compile package

### ISSUE THREAD

**Issue by orenyodfat** [daostack/arc.js#302]
I think the  same can be achieved using something like the following  code : 
https://github.com/daostack/arc.js/blob/orenyodfat-patch-1/getArcContracts.js

**Comment by dkent600** [comment]
@orenyodfat Thanks, can you please add an explanation for how this script migrates contracts?  Are we to do a manual `.new` and write the resulting address and txHash to the contract JSON ourselves?

Note that the code appears to be almost identical to what Arc.js `Utils.requireContract` does.

**Comment by dkent600** [comment]
Closing as it is not clear how this accomplishes a migration.  It only appears to load a raw truffle `Contract` that has not necessarily been deployed to a network.
