### ISSUE TITLE
Support deployment of non-universal schemes

### ISSUE THREAD

**Issue by orenyodfat** [daostack/arc.js#330]
There are some arc's none universal schemes which have some specific parameters sets at the constructor according to the dao specific needs.
e.g https://github.com/daostack/arc/tree/master/contracts/schemes 

arc.js should be able to deploy and support these schemes for clients which would like to include these scheme in their dao.

arc.js should provide 'createDao' function which get a list of schemes + dao parameters (this can be in a form of a json file ) ...if one of the schemes is not deployed arc.js should deploy that for the client (with the specific params) and create the dao.

**Comment by dkent600** [comment]
The proposal is for `DAO.new` to automatically instantiate any given scheme that has either not been deployed by Arc.js or has different constructor parameters than the scheme deployed by Arc.js.

Such a scheme would be presumed to have a wrapper in Arc.js, but would not be presumed to have `setParameters` and `getParameters` functions.  Arc.js would poke the address of the newly-instantiated scheme into the contract.json truffle artifact file supplied by Arc.

The application would then be able to obtain the wrapper at runtime using the `wrapperFactory.deployed()`.

The problem with this scenario is that whenever the application reinstalls Arc.js, the contract.json file would be replaced and the DAO would have to be recreated.

**Comment by orenyodfat** [comment]
DAO.new can behave as follow : 
 - if no address is provide to scheme , it will look at the contract.json for an address . 
   If the address not found it will deploy the scheme .
 - If address is provided it will use this address. 

In any case DAO.new should return all address of the dao( schemes, controller,organs...)

**Comment by dkent600** [comment]
@orenyodfat 

> If the address not found it will deploy the scheme
> In any case DAO.new should return all address of the dao( schemes, controller,organs...)

`DAO.new` returns a `DAO` object, which is really what it should do.  I am not inclined to change that behavior.  `DAO.getSchemes` lets you obtain a list of the DAO's schemes, along with the wrapper objects for addresses _that correspond to contracts that were originally migrated by arc.js_ (arc.js-scripts contains a script that does the same thing).  Any contract instantiated by `DAO.new` would not meet that last criteria, so its wrapper would not be returned.  If multiple contracts were instantiated this way during a single call to `DAO.new`, the caller would not know which address corresponds to which newly-instantiated contract.  This is not a good solution.

Thus I think it is best if the user be responsible for instantiating these contracts themselves in a separate operation.

On a side note:  The inability to recognize a contract given an address, unless it happens to be an instance deployed by the currently running version of arc.js, is a significant, long-standing problem with impacts beyond this immediate issue. There is an old ticket on it:  #8.

**Comment by dkent600** [comment]
The only alternative to "If the address not found it will deploy the scheme" would be for `DAO.new` to return a mapping of scheme names to their addresses (in addition to the new `DAO` object that it currently returns).

As described in the previous comment in this ticket, with respect to newly-instantiated schemes, this information would only be known at the time of calling `DAO.new`, and is not later obtainable.

I am mentioning this option just for the record, though I am not in favor of it.  I think some (most?) users are going to prefer to instantiate custom schemes using separate scripts, and it would be best for us to support those efforts. 

Consider the scenario of swapping-out contracts.  Suppose you create a DAO with scheme #1, then decide you want to swap it with scheme #2 without creating a new DAO.  In that case you need a script to create scheme #2.

What we most need in any case is a means of mapping any given address to its Arc contract name, as described in the previous comment in this ticket.
