### ISSUE TITLE
take "deployed" contract addresses from the new DAOstack migrations repo

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#371]
take "deployed" contract addresses from the new DAOstack migrations repo.  use them when calling `deployed` on the factory methods.

**Comment by jellegerbrandy** [comment]
I think it would be much much much better if this were a configuration option. I.e. if we could pass json with contract names and addresses to the `initialize(...)` function.

**Comment by dkent600** [comment]
> I think it would be much much much better if this were a configuration option. I.e. if we could pass json with contract names and addresses to the initialize(...) function.

That an be an option, the default addresses will come from the DAOstack migration package.

**Comment by jellegerbrandy** [comment]
Just a heads up: it may be easier to simply not use the `deployed` method at all. Instead, you could pass all the needed contract addresses at initialize, and only use the `at` method in your code.

**Comment by dkent600** [comment]
>  only use the at method in your code

That is exactly how I"m doing it.
