### ISSUE TITLE
arc.js  is not getting the right params from the genesisprotocol in arc.56

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/arc.js#376]
the `parameters` function of the GenesisProtocol has changed, and is not return the daobounty parameters that arc.js expects.

arc.js fails right here: https://github.com/daostack/arc.js/blob/master/lib/wrappers/genesisProtocol.ts#L896

This is probably a bug in arc: https://github.com/daostack/infra/issues/28

But it should have been caught by an arc.js test :-)

**Comment by dkent600** [comment]
We are just stubbing this code out for now.

**Comment by dkent600** [comment]
Fixed in v93
