### ISSUE TITLE
Add support for other networks besides kovan and ropsten?

### ISSUE THREAD

**Issue by dkent600** [daostack/Arc.js#39]
truffle.js currently references mainnet (live), ganache, kovan and ropsten.  Should we provide support for others?

(This has implications for the alchemy demo as well, in terms of how it validates that it is running against the network to which it has been targeted at build time.)

**Comment by tibetsprague** [comment]
Figure out which networks we want and their ids

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add support for other networks besides kovan and ropsten?](https://trello.com/c/V3Q2N6iE/30-add-support-for-other-networks-besides-kovan-and-ropsten)

**Comment by leviadam** [comment]
I think Mainnet, Kovan, Rinkbey, Ropstain.

**Comment by leviadam** [comment]
Although for MVP I'm willing to agree on Mainnet, Kovan  and ganache.

**Comment by dkent600** [comment]
Each network should have a distinct port# in the Url, per this guidance:  http://truffleframework.com/tutorials/deploying-to-the-live-network

**Comment by dkent600** [comment]
I'm putting kovan on port 8547, mainnet (live) on port 8546.  Ganache remains on 8545.

ropsten is still in there, though not tested, at port 8548

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor Arc-Js](https://trello.com/c/tZB40Yzd/34-refactor-arc-js)

**Comment by dkent600** [comment]
Closing as this is all done for everything except Rinkbey, which is lower priority than the others.  Will create a separate issue for Rinkbey.
