### ISSUE TITLE
Figure out consistent way to handle Events in the contract wrappers

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc.js#41]
We need a consistent, easy way to pull all logged events from a contract, as well as watch for future events. We could just fall back on Truffle's handling, and just document that, or we could do something in the wrappers to make it even easier to pull and analyze the logs for Events. 

For example it should be easy to pull all the created DAOs from the GenesisScheme, and watch for future created DAOs.

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Figure out consistent way to handle Events in the contract wrappers](https://trello.com/c/eLzHPpRj/39-figure-out-consistent-way-to-handle-events-in-the-contract-wrappers)

**Comment by dkent600** [comment]
The suggestion to have a way to obtain created DAOs is represented in #40

**Comment by dkent600** [comment]
One thing we could do for typescript programmers would be to add each contract's event functions to the d.ts.  @tibetsprague has already done this in one or two cases, and if done once then should be done for all.  This should include documenting the events and their parameters, which would flow to the automatically-generated API docs and thus also benefit javascript programmers as well.

Another thing can be to create custom subclasses of `ArcTransactionResult` that pull information out of the transaction logs generated by specific contract methods.  An example of where this is already being done is `ArcTransactionAgreementResult` which leverages the existing method `ArcTransactionResult.getValueFromTx`.

**Comment by dkent600** [comment]
Done
