### ISSUE TITLE
Scope environment variable names used in the arc-js configuration module

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#42]
We should scope the environment variable names used in the arc-js config module with a prefix like "arcjs_", so they don't conflict with other variables in the environment.

Example: "arcjs_network"

**Comment by dkent600** [comment]
@tibetsprague FYI

**Comment by tibetsprague** [comment]
sounds good to me

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scope environment variable names used in the arc-js configuration module](https://trello.com/c/kOvhmP9L/52-scope-environment-variable-names-used-in-the-arc-js-configuration-module)

**Comment by dkent600** [comment]
Done
