### ISSUE TITLE
Refactor/improve ContributionReward

### ISSUE THREAD

**Issue by tibetsprague** [daostack/Arc.js#43]
proposeContributionReward should return a "Proposal" object that you can pull log values from, vote on, see how many votes it has... Then we can move voting functionality out of Organization and into Proposals

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor/improve ContributionReward](https://trello.com/c/XdiIJnPd/49-refactor-improve-contributionreward)

**Comment by dkent600** [comment]
@tibetsprague  Should it also return the transaction, to be consistent with the other wrapper methods?

Perhaps we need to create a base interface for what is returned by all methods, one that, for now, just includes the transaction (or perhaps an array of one or more transactions).  Then methods like proposeContributionReward can add stuff to it like the proposal id (or a proposal class instance).

**Comment by dkent600** [comment]
> create a base interface for what is returned by all methods, one that, for now, just includes the transaction (or perhaps an array of one or more transactions). 

I will make this part of https://trello.com/c/tZB40Yzd

**Comment by tibetsprague** [comment]
I dont think it should be a part of that massive card personally :) my suggestion is to return a useful object instead of a transaction but maybe we need to think more high level about this as you suggested. I dont like it when functions return multiple things though. my suggestion is based on wanting the library to be provide more value and make it easier to do things with proposals

**Comment by dkent600** [comment]
@tibetsprague 

I'm closing because we are now returning a proposalId from everything contract handler method that generates a transaction.
