### ISSUE TITLE
Respect web3.eth.defaultAccount as default from for all transactions

### ISSUE THREAD

**Issue by tibetsprague** [daostack/Arc.js#45]
Right now when you call a transaction on a contract it always uses web3.eth.accounts[0] as the sender because that is what truffle does, unless you pass in a { from : XXX} option. This makes it hard to do our own account management, which is really important for testing. One easy fix would be to set contract.defaults({ from : getDefaultAccount() }) in ExtendTruffleContract, and in fact we already do this in requireContract! So we just need to add that to the constructor of ExtendTruffleContract. The only problem with this is it won't update the from address if the defaultAccount changes and we keep using the same instance of the contract, but I think its good enough of a solution for now. 

An even better solution might be to somehow override the sendTransaction function on ExtendTruffleContract, if thats possible, to always use getDefaultAccount(), unless a from option is passed in. Not sure how easy this would be.

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Respect web3.eth.defaultAccount as default from for all transactions](https://trello.com/c/HybXJwMR/55-respect-web3ethdefaultaccount-as-default-from-for-all-transactions)

**Comment by dkent600** [comment]
> The only problem with this is it won't update the from address if the defaultAccount changes

In that case, when the default account changes, you must call `InitializeArcJs` to reinitialize everything that defaults on the default account.
