### ISSUE TITLE
Should the lib folder be included in the NPM ?

### ISSUE THREAD

**Issue by orenyodfat** [daostack/arc.js#48]

**Comment by dkent600** [comment]
The tests run against the lib folder.  They could be made to point to the dist folder, but that would force the developer to run a build between every test run, which is inconvenient and not necessarily desired.

package-script.js references `config.js` from the lib folder, but I think this should probably be changed to the dist folder.

**Comment by dkent600** [comment]
I expect that once #58 is done then we will no longer have need to publish the lib folder.  Tests will run against the dist folder.

**Comment by dkent600** [comment]
We are including it for typescript sourceMaps to point to, enhancing the application debugging experience.
