### ISSUE TITLE
Fix support for plugin manager

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/arc.js#484]
Pluginmanager broke when upgrading arc to rc.20

I have released a new version `2.0.0-experimental.38` on the basis of https://github.com/daostack/arc.js/pull/482 in any case, because I need the support, but the plugin tests are still failing there still

**Comment by dOrgJelli** [comment]
@jellegerbrandy this was what was missing: https://github.com/daostack/arc.js/pull/482/commits/1dd855bb195043a85dfd4c20f86ebccdb7402f26
