### ISSUE TITLE
release 49 not working in react native

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/arc.js#519]
I get the following error `error: bundling failed: Error: Unable to resolve module `crypto` from `node_modules/ethers/utils/random-bytes.js`: crypto could not be found within the project.` that I know is related to the way functions are imported from ethers.js 

Version 48 is working fine

**Comment by orenyodfat** [comment]
how to reproduce ?

**Comment by jellegerbrandy** [comment]
fixed in https://github.com/daostack/arc.js/releases/tag/2.0.0-experimental.53
