### ISSUE TITLE
use BN and not BigNumber

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/arc.js#529]
Arc.js uses both BN (standalone lib) and BigNumber (imported from ethers.js) to represent large numbers. 

This is not consistent and therefore not good. 

We use BigNumber only in a few places (Arc.ts and token.ts); in all other places we use BN.  

So, to have a consistent solutionwe should probably stick to BN in the whole code base.

**Comment by orenyodfat** [comment]
seems like ethers.js use its own BigNumber .
is use BN.js internally.
https://docs.ethers.io/v5/api/utils/bignumber/#BigNumber--BigNumber--notes--why-not-bignumber-js-bn-js-bigdecimal-etc
