### ISSUE TITLE
Creating a new DAO should not assume a particular voting machine

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#56]
Currently when we create a new DAO, in `GenesisScheme.setSchemes` we assume that any passed-in voting machine addresses are for an AbsoluteVote.  We must not make this assumption.

**Comment by dkent600** [comment]
What are the options?

**Comment by dkent600** [comment]
We have to be able to call `<votingMachine>.setParameters` because, at least for AbsoluteVote, it requires a reputation address that isn't available until after calling `DaoCreator.forgeOrg`, and (I'm pretty sure) `DaoCreator.setSchemes` will fail if it has not been called.

But then we have to know how to call setParameters for every possible voting machine.  The handler classes nicely encapsulate this knowledge, but given just a voting machine address, we can't know for sure what handler to use.  

Perhaps the solution is:

1)  require that the caller supply the name of the voting machine, so we can get its handler
2) when the voting machine does not have a handler (is not a known Arc contract), then the caller should provide a callback whereby the parameters will be registered.

**Comment by tibetsprague** [comment]
yeah i actually now need it to start using GenesisProtocol as the default. or i guess ill just have to write my own dao creation for now

**Comment by tibetsprague** [comment]
i do think passing in the voting machine name makes sense for now

**Comment by dkent600** [comment]
@tibetsprague 

> yeah i actually now need it to start using GenesisProtocol as the default.

Are you going to use GenesisProtocol as a scheme registered to the DAO (as the Arc test code does), or as a voting machine on one or more of the other schemes registered to the DAO?

**Comment by dkent600** [comment]
Haven't done "when the voting machine does not have a handler (is not a known Arc contract), then the caller should provide a callback whereby the parameters will be registered."  Will create a separate issue to that.
