### ISSUE TITLE
Automate creation of API documentation

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#63]
Code comments should be formatted as JSDoc.  Conversion to markdown using:  https://github.com/jsdoc2md/jsdoc-to-markdown

**Comment by dev-matan-tsuberi** [comment]
Also use `mkdocs` & `mkdocs material` to create a documentation website just like in `daostack/Arc`

**Comment by dkent600** [comment]
See @dev-matan-tsuberi 's [example of how to make this work.](https://github.com/dev-matan-tsuberi/arc.js/commit/3e4dadbfa134291971493525c1832870c6b3a318)

**Comment by dkent600** [comment]
I have not found a way to make jsdoc-to-markdown work with typescript, and I don't believe it is designed to.  Moving on to typedoc.

**Comment by dkent600** [comment]
How to proceed with this:  

1) Convert all javascript to typescript (#58)
2) Move all docs out of the d.ts and into the typescript code itself.  (I think this is better anyway)

Comments should be formatted according [to this](typedoc.org/guides/doccomments/).

**Comment by dev-matan-tsuberi** [comment]
You should use:
https://www.npmjs.com/package/typedoc-markdown-theme
Or
https://www.npmjs.com/package/typedoc-plugin-markdown

To get markdown output from TypeDoc.

**Comment by dkent600** [comment]
@dev-matan-tsuberi  Typedoc generates html by default.  I was going to try taking that straight to the git page, no need for md.  What do you think?

**Comment by dev-matan-tsuberi** [comment]
@dkent600 I think we should be consistent with the way the website looks. let's stick with `mkdocs` and generate only `.md` using TypeDoc.

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Automate creation of API documentation](https://trello.com/c/B5rY1F0A/69-automate-creation-of-api-documentation)

**Comment by dkent600** [comment]
Done
