### ISSUE TITLE
Add getVotingMachine function to each scheme that has one

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#72]
For every scheme that has a voting machine as a parameter, add a function that returns it, given the controller with which the scheme is registered.

(I think...gotta make sure the separation of concerns is right with that.....)

**Comment by tibetsprague** [comment]
I think there should be a generic way to add this to a scheme wrapper, instead of having to implement it for each scheme. but maybe im wrong :)

**Comment by dkent600** [comment]
There will be a generic base class method, but the parameter index for each scheme is potentially different.

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add getVotingMachine function to each scheme that has one](https://trello.com/c/5A1PzjVZ/72-add-getvotingmachine-function-to-each-scheme-that-has-one)

**Comment by dkent600** [comment]
Make this part of #116 ?

**Comment by dkent600** [comment]
If possible, every voting machine wrapper should implement a common voting machine interface.
