### ISSUE TITLE
In ContributionReward.proposeContributionReward, should caller hash the description?

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#82]
Currently `ContributionReward.proposeContributionReward` hashes the description of the proposal.

Should the caller be responsible for doing the hashing?

If the caller is responsible for managing external storage of the unhashed description, then they may want to have the hash value to use as a key into their storage.  (See `ContributionReward.getDaoProposals` and #116 for how the caller can obtain the hash value.)

But is there any reason why the caller might need to be able to do the hashing themselves?

**Comment by dkent600** [comment]
@leviadam

**Comment by dkent600** [comment]
@tibetsprague What do you think?

**Comment by tibetsprague** [comment]
hmm, do we care how the hashing is done? my intuition is that we should do the hashing in arc.js but im not sure

**Comment by dkent600** [comment]
@leviadam @orenyodfat @tibetsprague  Closing due to lack of objection to the status quo.

**Comment by bohendo** [comment]
Having arc.js handle hashing is blocking progress on my recent [proposal to migrate data to IPFS](https://gitlab.com/bohendo/alchemy/blob/master/proposals/decentralize-proposal-data.md).

In the future, other clients might want to store data in IPFS. Or maybe clients will want to utilize Ethereum's swarm storage once it's ready. The current implementation lacks the flexibility of experimenting with these options.

**Comment by bohendo** [comment]
Don't stress about patching this, since I need to use old (ie currently deployed) contracts, it seems like I need to use a version of arc.js prior to 0.0.0-alpha.85 so I don't think I'd be able to use a new release even if it were available. I suspect I can work around this issue by calling this method manually w/out using the arc.js library.

**Comment by dkent600** [comment]
Reopening to consider @bohendo's issue
