### ISSUE TITLE
Add Enum type definitions for ProposalStates and VoteStatuses and other enums

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc.js#86]
e.g. 

```
export enum ProposalStates {
  Closed = "Closed",
  Executed = "Executed",
  NotBoosted = "NotBoosted",
  Boosted = "Boosted"
}

export enum VotesStatus {
  Yes = 1,
  No = 2
}
```

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Enum type definitions for ProposalStates and VoteStatuses and other enums](https://trello.com/c/gwzHdTyb/78-add-enum-type-definitions-for-proposalstates-and-votestatuses-and-other-enums)

**Comment by dkent600** [comment]
This would best be done after conversion to typescript, as enums don't exist in ES6.

**Comment by dkent600** [comment]
Should be part of #116

**Comment by dkent600** [comment]
ProposalStates is done

**Comment by dkent600** [comment]
VoteStatus is done (as `BinaryVoteResult`)
