### ISSUE TITLE
Utils.getValueFromLogs should return false for non existent events

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc.js#88]
When an event doesn't exist in the logs Utils.getValueFromLogs should return false instead of throwing an exception. This is because we often want to check if a transaction had an event, and if it did grab some log values from it, its easier to do that with boolean values than using try catch. Another option would be to add a second function to first check wether the logs contain the event.

**Comment by dkent600** [comment]
Returning false is not good because it is potentially a valid return value.

Better to add another function that checks for existence.

**Comment by tibetsprague** [comment]
right, sounds good

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Utils.getValueFromLogs should return false for non existent events](https://trello.com/c/TUTBSAWM/82-utilsgetvaluefromlogs-should-return-false-for-non-existent-events)

**Comment by dkent600** [comment]
@tibetsprague Or return undefined?

**Comment by tibetsprague** [comment]
that works!
