### ISSUE TITLE
Reduce perceived number of transactions when creating an organization

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#9]
We need to do whatever we can to reduce the impacts on the user of the large number of transactions involved in creating an organization, either by reducing the _actual_ number of transactions, or by reducing the _apparent_ number of transactions.

See comments here:
https://github.com/daostack/daostack/issues/47#issuecomment-315541742
https://github.com/daostack/daostack/issues/55

**Comment by dkent600** [comment]
Using `.call` could help?

See:  https://www.reddit.com/r/ethdev/comments/6knlyf/truffle_executing_a_function_vs_call_method/

**Comment by dkent600** [comment]
Though we are down to 6 transactions, I still want to confirm that the javascript is not creating any unnecessary transactions.

**Comment by tibetsprague** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Audit library to check for any unecessary transactions being made](https://trello.com/c/xz57eejh/35-audit-library-to-check-for-any-unecessary-transactions-being-made)

**Comment by dkent600** [comment]
When I run a quick test in Arc.js against Ganache, adding one founder and the three required schemes, I am seeing 12 transactions in the ganache output.

It looks like they may be divided into 7 from forgeOrg and 5 from setSchemes (not sure about that).

**Comment by dkent600** [comment]
Running the same test as above against Kovan, the Parity UI prompted me to approve eight transactions.

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reduce perceived number of transactions when creating an organization](https://trello.com/c/p5dO1RMc/77-reduce-perceived-number-of-transactions-when-creating-an-organization)

**Comment by dkent600** [comment]
See https://github.com/daostack/arc/issues/388#issuecomment-369642789

**Comment by dkent600** [comment]
I have been able to work-around Arc's lack of support for avoiding redundant saving of parameters, in this branch:  https://github.com/daostack/arc.js/tree/minimizeTransactions

Not pretty, but it works.  I find that in the case of Alchemy, we will be able to reduce the number of transactions to the bare minimum as follows:

1) incorporate the Arc.js changes in the above-referenced branch
2) make the Arc.js default GenesisProtocol parameters equal to the GenesisProtocol params of the Genesis DAO.  (This is not yet approved:  https://github.com/daostack/arc.js/issues/104)
3) set the Config.defaultVotingMachine to "GenesisProtocol"

This works as long as Alchemy uses the default parameters for GenesisProtocol, which it currently does do.

In the case where folks want to use AbsoluteVote as their voting machine, then there are going to be more transactions.

@tibetsprague

**Comment by tibetsprague** [comment]
this all sounds good to me

**Comment by dkent600** [comment]
We've done all we're going to do for now on this.  The only juice remaining to squeeze must come from Arc: https://github.com/daostack/arc/issues/388
