### ISSUE TITLE
The Genesis DAO should be created with GenesisProtocol and ContributionReward schemes

### ISSUE THREAD

**Issue by tibetsprague** [daostack/arc.js#90]
The Genesis DAO is as far as I understand it supposed to be the DAOstack DAO and thus should use the GenesisProtocol as its voting machine and have ContributionReward added to it as well.

**Comment by tibetsprague** [comment]
Also this is needed to transfer GEN tokens to accounts so they can then be used for staking proposals

**Comment by dkent600** [comment]
@tibetsprague Should also have GenesisProtocol added to it.

**Comment by dkent600** [comment]
Done
