### ISSUE TITLE
automatically generate d.ts (typings)

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#96]
Once we have all the code in typescript (#58), and the code is fully fleshed out with data types and return type definitions (#95), we should automate the generation of the d.ts file.  This will reduce the potential for errors arising from redundancy.

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [automate generation of d.ts (typings)](https://trello.com/c/YxBwjYVl/87-automate-generation-of-dts-typings)

**Comment by dkent600** [comment]
I've looked at several packages trying to find a tool that will generate a d.ts in the structure that we use.  I've posed a question on stackoverflow.  All to no avail, as yet.

What I do have is a set of steps to do this manually.  The process takes only a couple minutes.  I could probably write some code to automated this.

The steps:
```
1. Run:

	type dist/*.d.ts > index.d.ts
	type dist/contracts/*.d.ts >> index.d.ts

2. Remove the arc.ts imports at top.

3. Change all: "declare " to: ""

4. Remove all statements that start with "import "

5. Surround everything with:

	import * as BigNumber from "bignumber.js";
	declare module "@daostack/arc.js" {
	
		[everything]
	
	}
```

**Comment by tibetsprague** [comment]
yikes, thats crazy. what are other people doing?

**Comment by dkent600** [comment]
dunno, that is why I posed the question on stackoverflow.

**Comment by dkent600** [comment]
Done.  turned out to be easy (see the stackoverflow question)
