### ISSUE TITLE
Cease cloning the truffle contract into the wrapper class

### ISSUE THREAD

**Issue by dkent600** [daostack/arc.js#98]
I propose that we cease cloning the truffle contract into the wrapper class.  All the original truffle functionality should be limited to the `contract` property (where it currently already resides).

I think this practise of cloning is dangerous (no scientific/cultural commentary intended ;-) ).

Cloning as is being done now copies property _values_ and methods from the truffle contract.  Because only the _values) of properties are copied (not references to the properties), when anything changes that can effect the property values, the wrapper and `contract` property values can become out-of-sync with potentially bad consequences.

**Comment by dkent600** [comment]
@tibetsprague Any comment on this?

**Comment by dkent600** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cease cloning the truffle contract into the wrapper class](https://trello.com/c/3Ba7m4mx/89-cease-cloning-the-truffle-contract-into-the-wrapper-class)

**Comment by tibetsprague** [comment]
yeah I agree, that seems weird. where do we actually use that?

**Comment by dkent600** [comment]
@tibetsprague 
> where do we actually use that?

One uses it any time one calls a method on the contract, including event and property getters, that is not explicitly implemented by the wrapper itself, rather is implemented by the truffle contract.
